import { FaUser } from "react-icons/fa";
/* The `reportsData` constant is an array of objects. Each object represents a report and contains
information such as the reporter's name, avatar, reported user's name, report time, and status. */
const reportsData = [
  {
    key: 1,
    reporterName: "John Brown",
    avatar: <FaUser />,
    reportedUserName: "John Doe",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 2,
    reporterName: "Smith",
    avatar: <FaUser />,
    reportedUserName: "John Doe",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 3,
    reporterName: "Michael",
    avatar: <FaUser />,
    reportedUserName: "John Doe",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 4,
    reporterName: "Cillian",
    avatar: <FaUser />,
    reportedUserName: "Smurf",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 5,
    reporterName: "Murphy",
    avatar: <FaUser />,
    reportedUserName: "Clint",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 6,
    reporterName: "Steve",
    avatar: <FaUser />,
    reportedUserName: "Bruce",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 7,
    reporterName: "Tony",
    avatar: <FaUser />,
    reportedUserName: "Steve",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 8,
    reporterName: "Tom",
    avatar: <FaUser />,
    reportedUserName: "Phil",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 9,
    reporterName: "Timmy",
    avatar: <FaUser />,
    reportedUserName: "Phil",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 10,
    reporterName: "Jordan",
    avatar: <FaUser />,
    reportedUserName: "Phil",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 11,
    reporterName: "Casey",
    avatar: <FaUser />,
    reportedUserName: "Shonan",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 12,
    reporterName: "Shane",
    avatar: <FaUser />,
    reportedUserName: "Will",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 13,
    reporterName: "Arthur",
    avatar: <FaUser />,
    reportedUserName: "Bane",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 14,
    reporterName: "Mordok",
    avatar: <FaUser />,
    reportedUserName: "Syed",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
  {
    key: 15,
    reporterName: "Tank",
    avatar: <FaUser />,
    reportedUserName: "Top",
    reportTime: "23 June 10:00 AM",
    status: "Active",
  },
];
export default reportsData;
